<?php

namespace Database\Seeders;

use App\Models\DefaultServiceImplementationPlanDetail;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DefaultServiceImplementationPlanDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "id" => "8238e0fe-4dc2-450d-8799-6e6929d1a8b3",
                "value" => "Tujuan Khusus",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "d0984254-1263-4eba-b29e-33c3d9d10cba",
                "value" => "Materi Layanan",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "011e2a32-4d41-4dc9-b21e-4011540b3112",
                "value" => "Metode/Teknik",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "962bced8-0aa9-4aed-9aef-7cb12f6dc73a",
                "value" => "Ceramah",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "011e2a32-4d41-4dc9-b21e-4011540b3112",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "f25bb0af-0753-44aa-a31c-8453cae7af2e",
                "value" => "Curah pendapat",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "011e2a32-4d41-4dc9-b21e-4011540b3112",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "59739c16-1736-4c67-ad20-620567500766",
                "value" => "Tanya jawab",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "011e2a32-4d41-4dc9-b21e-4011540b3112",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "10dfd0dd-ea80-48ef-81cb-c6711d775a70",
                "value" => "Media/Alat",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "7c6e1e26-1133-475c-bc06-9e0de37eb0c1",
                "value" => "LCD",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "10dfd0dd-ea80-48ef-81cb-c6711d775a70",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "e71bf3b1-0588-4fd9-a0bd-a3c90dd29038",
                "value" => "Power Point Tuhan Selalu Hadir dalam Hidupku",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "10dfd0dd-ea80-48ef-81cb-c6711d775a70",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "e92f8a40-10b3-4803-9b34-7423df2b43db",
                "value" => "Pelaksanaan",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "68406a55-62d3-4d70-938b-1adbfa7f30a9",
                "value" => "Tahap Awal/Pendahuluan",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "e92f8a40-10b3-4803-9b34-7423df2b43db",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "1a295718-6ffa-42b5-9742-dcf8d2a1b529",
                "value" => "Pernyataan Tujuan",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "68406a55-62d3-4d70-938b-1adbfa7f30a9",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "6b92e426-e2df-48ae-8cdb-827c08df6158",
                "value" => "Salam",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1a295718-6ffa-42b5-9742-dcf8d2a1b529",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "cddc95c0-e36d-44a6-9954-bd7971121f8a",
                "value" => "Menanyakan kabar",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1a295718-6ffa-42b5-9742-dcf8d2a1b529",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "bc9c2463-a346-4bff-979e-3bded1dff6e6",
                "value" => "Ice breaker (berbagai macam variasi).",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1a295718-6ffa-42b5-9742-dcf8d2a1b529",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "b99654c4-fec9-4e0d-9810-154f81af85a8",
                "value" => "Menyampaikan tujuan yang akan dicapai",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1a295718-6ffa-42b5-9742-dcf8d2a1b529",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "1507be9b-8b85-4980-b2ed-34e05cdfa6a0",
                "value" => "Penjelasan tentang langkah-langkah kegiatan",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "68406a55-62d3-4d70-938b-1adbfa7f30a9",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "b16576ee-862a-40ba-be43-6eb2660007ef",
                "value" => "Memberikan langkah-langkah kegiatan, tugas dan tanggung jawab peserta didik",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1507be9b-8b85-4980-b2ed-34e05cdfa6a0",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "cba63df5-08e3-41b0-ac86-150fe8f7d2b6",
                "value" => "Kontrak layanan ( kesepakatan layanan ), hari ini kita akan melakukan kegiatan selama 1 jam pelayanan, kita sepakat akan melakukan dengan baik.",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "1507be9b-8b85-4980-b2ed-34e05cdfa6a0",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "3431be6f-2441-4565-88ca-abcac9c00317",
                "value" => "Mengarahkan kegiatan (konsolidasi)",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "68406a55-62d3-4d70-938b-1adbfa7f30a9",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "4e109dc4-494c-4448-926a-d9d7d2ec9369",
                "value" => "Guru BK/Konselor memberikan penjelasan tentang topik yang akan dibicarakan",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "3431be6f-2441-4565-88ca-abcac9c00317",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "24212e8d-272a-4fe2-839f-446de4380624",
                "value" => "Tahap peralihan (Transisi)",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "68406a55-62d3-4d70-938b-1adbfa7f30a9",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "82f9586e-4f69-4544-ae56-98c3c897f101",
                "value" => "Guru BK/Konselor menanyakan kesiapan peserta didik melaksanakan kegiatan, dan memulai ke tahap inti",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "24212e8d-272a-4fe2-839f-446de4380624",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "567d9dd7-9277-4529-9c81-8df820f50f58",
                "value" => "Tahap Inti",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "e92f8a40-10b3-4803-9b34-7423df2b43db",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "0ea23916-9bb7-4c05-b326-1a21d2f4c54d",
                "value" => "Kegiatan Peserta Didik",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "567d9dd7-9277-4529-9c81-8df820f50f58",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => Str::uuid(),
                "value" => "Peserta didik mengamati tayangan materi melalui media power point",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "0ea23916-9bb7-4c05-b326-1a21d2f4c54d",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "aefe2295-e035-4d5f-90ea-210ec24102c1",
                "value" => "Kegiatan Guru BK/Konselor",
                "level" => 2,
                "default_service_implementation_plan_detail_id" => "567d9dd7-9277-4529-9c81-8df820f50f58",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "6e491db5-27fe-4162-96d8-591c93cab777",
                "value" => "Tahap Penutup",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "e92f8a40-10b3-4803-9b34-7423df2b43db",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "dfa0db9b-a565-4414-9e58-a9ed1ad76db2",
                "value" => "Guru BK/Konselor memberikan penguatan",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "6e491db5-27fe-4162-96d8-591c93cab777",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "00c057e8-dc90-420f-88bf-594252cdcf8c",
                "value" => "Merencanakan tindak lanjut",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "6e491db5-27fe-4162-96d8-591c93cab777",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "712e8165-2bbd-4359-ad5b-ff6077954fc8",
                "value" => "Evaluasi",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "2d0954ba-c2e8-4dcb-8135-f28efbacaecf",
                "value" => "Evaluasi Proses",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "712e8165-2bbd-4359-ad5b-ff6077954fc8",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "c02eea68-dd64-48e4-84d4-a2126a662983",
                "value" => "Melakukan Refleksi hasil, setiap peserta didik menuliskan di kertas yang sudah disiapkan.",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "2d0954ba-c2e8-4dcb-8135-f28efbacaecf",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "7b7e8185-e27b-45d3-9ae0-6e4d4c513368",
                "value" => "Sikap atau antusias peserta didik dalam mengikuti kegiatan",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "2d0954ba-c2e8-4dcb-8135-f28efbacaecf",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "4da6fc22-e3a1-425a-a513-5b0ec46bde4a",
                "value" => "Cara peserta didik dalam menyampaikan pendapat atau bertanya",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "2d0954ba-c2e8-4dcb-8135-f28efbacaecf",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "31e7562f-c3fa-4c33-9f99-7bd07fab9265",
                "value" => "Cara peserta didik memberikan penjelasan dari pertanyaan guru BK",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "2d0954ba-c2e8-4dcb-8135-f28efbacaecf",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "4845794d-a476-46c3-9674-3637d54712a2",
                "value" => "Evaluasi Hasil",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "712e8165-2bbd-4359-ad5b-ff6077954fc8",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "d8dce292-bf83-4618-a8ba-bd6572eb7a44",
                "value" => "Merasakan suasana pertemuan: menyenangkan/kurang menyenangkan/tidak menyenangkan",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "4845794d-a476-46c3-9674-3637d54712a2",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "000d3668-6680-4c4b-a37f-1a3497cf751f",
                "value" => "Topik yang dibahas:sangat penting/kurang penting/tidak penting",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "4845794d-a476-46c3-9674-3637d54712a2",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "6bd115b4-4716-4a44-bb9b-8daa9c0c4803",
                "value" => "Penyampaian Guru BK/Konselor: mudah dipahami/sulit dipahami",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "4845794d-a476-46c3-9674-3637d54712a2",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "61b187a3-5aa3-4d22-949d-fb06d166aad8",
                "value" => "Kegiatan yang diikuti:menarik/kurang menarik/tidak menarik untuk diikuti",
                "level" => 3,
                "default_service_implementation_plan_detail_id" => "4845794d-a476-46c3-9674-3637d54712a2",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "198a7a35-09dc-44f3-b0a1-3d179271893c",
                "value" => "Lampiran",
                "level" => 0,
                "default_service_implementation_plan_detail_id" => null,
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "c2f17163-5b56-4af7-a2e7-861569f24bbc",
                "value" => "Uraian materi/Slide power point",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "198a7a35-09dc-44f3-b0a1-3d179271893c",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],
            [
                "id" => "8df0fc6c-499a-4b33-ad15-8d4ef673b832",
                "value" => "Lembar kerja siswa",
                "level" => 1,
                "default_service_implementation_plan_detail_id" => "198a7a35-09dc-44f3-b0a1-3d179271893c",
                "school_id" => null,
                "created_at" => round(microtime(true) * 1000),
                "service_strategy" => "klasikal",
            ],

        ];

        for ($i = 0; $i < count($data); $i++) {
            $insert = new DefaultServiceImplementationPlanDetail;
            $insert->id                 = $data[$i]['id'];
            $insert->value               = $data[$i]['value'];
            $insert->service_strategy               = $data[$i]['service_strategy'];
            $insert->default_service_implementation_plan_detail_id               = $data[$i]['default_service_implementation_plan_detail_id'];
            $insert->created_at               = $data[$i]['created_at'] + $i;
            $insert->save();
        }
    }
}
